name: SandWands
author: nbdSteve
version: ${project.version}
main: dev.nuer.sand.SandWands
api-version: 1.13
commands:
  sw:
    usage: /<command>
    description: Type '/sw help' for command help.
  sand:
    usage: /<command>
    description: Type '/sw help' for command help.
