name: SandWands
author: nbdSteve
version: 3.1.4-[MC-1.13+]
main: dev.nuer.sand.SandWands
api-version: 1.13
commands:
  sw:
    usage: /<command>
    description: Type '/sw help' for command help.
  sand:
    usage: /<command>
    description: Type '/sw help' for command help.
